[package]
name = "brainfeed"
version = "0.1.0"
authors = ["panicbit <panicbit.dev@gmail.com>"]
edition = "2018"

[dependencies]
pest = "2.1.1"
pest_derive = "2.1.0"
lazy_static = "1.3.0"

[dev-dependencies]
minibf = { path = "minibf" }

[workspace]
